### ISSUE TITLE
More background info.

### ISSUE THREAD

**Issue by mishelashala** [staltz/prevent-smoosh#1]
Could you give more background about why replacing flatten with smoosh is a bad idea?

**Comment by staltz** [comment]
- Non-standard name for flatMap (it has had many names, but never smooshMap)
- To understand the concept, searching on the web flatMap gives many good resources already
- Smoosh can have [very bad connotations](https://www.urbandictionary.com/define.php?term=Smoosh%20Smoosh)
- The community is not receiving it well
