### ISSUE TITLE
Prevent the use of flat as well

### ISSUE THREAD

**Issue by R2D221** [staltz/prevent-smoosh#6]
According to this tweet, the “smoosh” name is being dropped, and “flat” will be used instead. We should apply the same logic to this new term.

**Comment by R2D221** [comment]
https://mobile.twitter.com/mathias/status/999101901697363969

**Comment by TrySound** [comment]
@R2D221 This is a good name. Can you suggest a better one?

**Comment by R2D221** [comment]
Flatten.

**Comment by TrySound** [comment]
@R2D221 You know the problem if you are here. We should not break the web not matter how old stuff it has. This is ok position I think.

**Comment by R2D221** [comment]
I thought the point of this project was to make a point about not catering for any specific implementation, hence why the smoosh methods were made incompatible with the proposal. Or am I missing something?

**Comment by R2D221** [comment]
Seems like I did indeed misunderstand the purpose of this project, then.
